[workspace]
members = [
  "bin",
  "core",
  "pymodule",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
bincode = "1.3.3"
byteorder = "1.5.0"
libc = "0.2.153"
pyo3 = "0.20.3"
serde = { version = "1.0.197", features = ["derive"] }
